#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -fr $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

rm -fr $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -fr $HOME/Library/Application\ Support/com.mitchellh.ghostty/config
ln -s $DOTFILES/ghostty/config $HOME/Library/Application\ Support/com.mitchellh.ghostty/config

rm -fr $HOME/.config/starship.toml
ln -s $DOTFILES/starship/starship.toml $HOME/.config/starship.toml
